In [1]:
import numpy as np
import math 
from qiskit import QuantumCircuit,ClassicalRegister, QuantumRegister, transpile

import qiskit.quantum_info as qi
from qiskit.visualization import plot_state_city, array_to_latex
import sympy 
import qutip
#np.set_printoptions(precision=3) #"rounding"
#np.set_printoptions(suppress=True) #supressing scientific format"
import itertools
from math import pi

In [2]:
exp_idt = np.array([[1,0,0,0],[-1.8e-4,0.9367337,-0.0039314,-0.0047254],[0.023309,0.0138398,0.9353173,-0.0304966],[0.0108652,-0.0088714,0.0174195,0.9827782]])
exp_idt

array([[ 1.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00],
       [-1.800000e-04,  9.367337e-01, -3.931400e-03, -4.725400e-03],
       [ 2.330900e-02,  1.383980e-02,  9.353173e-01, -3.049660e-02],
       [ 1.086520e-02, -8.871400e-03,  1.741950e-02,  9.827782e-01]])

In [3]:
ptm_exp=qi.PTM(exp_idt)
ptm_exp.is_cp()

True

In [4]:
exp_kraus=qi.Kraus(ptm_exp)
exp_kraus

Kraus([[[-9.84447177e-01-7.67061139e-18j,
          1.00575460e-03+1.82351449e-02j],
        [-1.08968355e-03+6.25615662e-03j,
         -9.78901978e-01-9.19498996e-03j]],

       [[ 1.65023859e-01+1.11919744e-16j,
         -2.33835912e-02+6.76081710e-02j],
        [-2.61524190e-02+1.34541614e-02j,
         -1.64599834e-01-8.88894484e-04j]],

       [[-2.11870785e-02-9.61573170e-13j,
         -1.86002119e-02+9.02436736e-02j],
        [-3.72900574e-02-1.83890758e-02j,
          2.28844708e-02+9.12955294e-04j]],

       [[ 1.92082893e-03+1.27804730e-12j,
          9.98453264e-03-1.65270430e-03j],
        [ 1.40487498e-04-2.33298818e-02j,
         -2.09978304e-03-1.82342898e-04j]]],
      input_dims=(2,), output_dims=(2,))

In [5]:
krausf=np.array([[[-9.84447177e-01-7.67061139e-18j,
          1.00575460e-03+1.82351449e-02j],
        [-1.08968355e-03+6.25615662e-03j,
         -9.78901978e-01-9.19498996e-03j]],

       [[ 1.65023859e-01+1.11919744e-16j,
         -2.33835912e-02+6.76081710e-02j],
        [-2.61524190e-02+1.34541614e-02j,
         -1.64599834e-01-8.88894484e-04j]],

       [[-2.11870785e-02-9.61573170e-13j,
         -1.86002119e-02+9.02436736e-02j],
        [-3.72900574e-02-1.83890758e-02j,
          2.28844708e-02+9.12955294e-04j]],

       [[ 1.92082893e-03+1.27804730e-12j,
          9.98453264e-03-1.65270430e-03j],
        [ 1.40487498e-04-2.33298818e-02j,
         -2.09978304e-03-1.82342898e-04j]]])

In [6]:
krausf[0]

array([[-0.98444718-7.67061139e-18j,  0.00100575+1.82351449e-02j],
       [-0.00108968+6.25615662e-03j, -0.97890198-9.19498996e-03j]])

In [7]:
from sympy.physics.quantum import TensorProduct
i = np.array([[1, 0], [0, 1]])
x = np.array([[0, 1], [1, 0]])
y = np.array([[0,-1j],[1j,0]])
z = np.array([[1, 0], [0,-1]])

In [8]:
from itertools import product
def coefficients(kraus_list,q_number):
    paulis = list(product([i,x,y,z],repeat=q_number))
    spaulis = list(product(['i','x','y','z'],repeat=q_number))
    #print(spaulis)
    result = []
    for k_index,kraus in enumerate(kraus_list,start=0):
        print(kraus,'*')
        for index, pauli in enumerate(paulis, start=0):
            print(pauli[0])
            a = 1/2*np.trace(np.matmul(kraus,pauli[0]))
            #b=1/2*np.trace(a)
            #print(b)
            result.append((a,spaulis[index],k_index))
    return result

In [9]:
coef = coefficients(krausf,1)
coef

[[-0.98444718-7.67061139e-18j  0.00100575+1.82351449e-02j]
 [-0.00108968+6.25615662e-03j -0.97890198-9.19498996e-03j]] *
[[1 0]
 [0 1]]
[[0 1]
 [1 0]]
[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
[[ 1  0]
 [ 0 -1]]
[[ 0.16502386+1.11919744e-16j -0.02338359+6.76081710e-02j]
 [-0.02615242+1.34541614e-02j -0.16459983-8.88894484e-04j]] *
[[1 0]
 [0 1]]
[[0 1]
 [1 0]]
[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
[[ 1  0]
 [ 0 -1]]
[[-0.02118708-9.61573170e-13j -0.01860021+9.02436736e-02j]
 [-0.03729006-1.83890758e-02j  0.02288447+9.12955294e-04j]] *
[[1 0]
 [0 1]]
[[0 1]
 [1 0]]
[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
[[ 1  0]
 [ 0 -1]]
[[ 0.00192083+1.27804730e-12j  0.00998453-1.65270430e-03j]
 [ 0.00014049-2.33298818e-02j -0.00209978-1.82342898e-04j]] *
[[1 0]
 [0 1]]
[[0 1]
 [1 0]]
[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
[[ 1  0]
 [ 0 -1]]


[((-0.9816745775-0.004597494980000004j), ('i',), 0),
 ((-4.1964474999999966e-05+0.01224565076j), ('x',), 0),
 ((-0.00598949414+0.001047719075j), ('y',), 0),
 ((-0.0027725994999999726+0.004597494979999997j), ('z',), 0),
 ((0.00021201249999999727-0.00044444724199994406j), ('i',), 1),
 ((-0.0247680051+0.040531166199999996j), ('x',), 1),
 ((-0.0270770048+0.0013844138999999991j), ('y',), 1),
 ((0.1648118465+0.00044444724200005595j), ('z',), 1),
 ((0.0008486961499999997+0.00045647764651921344j), ('i',), 2),
 ((-0.02794513465+0.0359272989j), ('x',), 2),
 ((-0.0543163747+0.00934492275j), ('y',), 2),
 ((-0.02203577465-0.0004564776474807866j), ('z',), 2),
 ((-8.947705499999991e-05-9.117144836097636e-05j), ('i',), 3),
 ((0.005062510069-0.01249129305j), ('x',), 3),
 ((-0.010838588750000001+0.004922022571j), ('y',), 3),
 ((0.002010305985+9.117144963902366e-05j), ('z',), 3)]

In [10]:
from collections import defaultdict
d = defaultdict(complex)
for c, name, n in coef:
    #print(c,name, n)
    d[name] += abs(c) *abs(c).round(4)
 
d

defaultdict(complex,
            {('i',): (0.9637217240830237+0j),
             ('x',): (0.0046585685899766995+0j),
             ('y',): (0.0039502946213134755+0j),
             ('z',): (0.027678998503232462+0j)})

In [17]:
1/2*np.trace(np.matmul(krausf[0],x))

(-4.1964474999999966e-05+0.01224565076j)

In [16]:
1/2*np.trace(np.matmul(krausf[1],i))

(0.00021201249999999727-0.00044444724199994406j)