In [1]:
import numpy as np
import math 
from qiskit import QuantumCircuit,ClassicalRegister, QuantumRegister, transpile

import qiskit.quantum_info as qi
from qiskit.visualization import plot_state_city, array_to_latex
import sympy 
import qutip
#np.set_printoptions(precision=3) #"rounding"
#np.set_printoptions(suppress=True) #supressing scientific format"
import itertools
from math import pi

In [2]:
rx_piover2 = np.array([[ 0.707+0.j   , -0.   -0.707j],
       [ 0.   -0.707j,  0.707+0.j   ]])
rx_piover2

array([[ 0.707+0.j   , -0.   -0.707j],
       [ 0.   -0.707j,  0.707+0.j   ]])

In [3]:
ry_piover2 = np.array([[ 0.707+0.j, -0.707+0.j],
       [ 0.707+0.j,  0.707+0.j]])
rz_piover2= np.array([[0.707-0.707j, 0.   +0.j   ],
       [0.   +0.j   , 0.707+0.707j]])

In [2]:
xi=np.genfromtxt('/home//experimental_process_matrices/SkylineData_Giy_col1.csv',delimiter=',')#ix
xi
#xi.shape

array([[ 1.00000000e+00, -8.86511593e-17,  4.53487048e-34,
        -7.85046229e-17,  2.88108857e-34, -2.41587815e-35,
        -1.87159230e-35, -3.51488874e-35,  5.63142334e-34,
         1.15953039e-35, -3.61479913e-35,  1.93071706e-35,
        -8.45196016e-36, -5.73501300e-35, -3.13108020e-33,
         7.26299160e-35],
       [-8.13103583e-17,  3.92146130e-02,  3.27298531e-02,
         9.91456739e-01, -4.58143401e-07, -1.40928211e-05,
        -4.81285248e-04,  1.65721859e-05,  2.34419656e-07,
        -2.77174096e-05, -9.45583957e-04,  3.25604225e-05,
        -1.46403996e-11, -2.84276786e-03, -8.08925466e-02,
         2.80004153e-03],
       [ 1.07615233e-18,  1.73912556e-02,  9.74582753e-01,
        -3.33471737e-02, -1.69781182e-06, -7.35584319e-04,
         3.03808404e-05,  5.08110777e-04,  8.68770355e-07,
        -1.44529326e-03,  5.96907737e-05,  9.98276544e-04,
        -5.47593109e-11, -1.25027852e-01,  5.12906090e-03,
         8.52138403e-02],
       [ 8.45156022e-17, -9.78056726e

In [3]:
xi_ = qi.PTM(xi)
xi_.is_cp()

True

In [4]:
M,N = xi.shape
A=4
xi_trace_elements = xi[0:M-M%A, 0:N-N%A].reshape(M//A, A, -1, A).swapaxes(1, 2).reshape(-1, A, A)
xi_trace_elements

array([[[ 1.00000000e+00, -8.86511593e-17,  4.53487048e-34,
         -7.85046229e-17],
        [-8.13103583e-17,  3.92146130e-02,  3.27298531e-02,
          9.91456739e-01],
        [ 1.07615233e-18,  1.73912556e-02,  9.74582753e-01,
         -3.33471737e-02],
        [ 8.45156022e-17, -9.78056726e-01,  1.85175096e-02,
          2.78997635e-02]],

       [[ 2.88108857e-34, -2.41587815e-35, -1.87159230e-35,
         -3.51488874e-35],
        [-4.58143401e-07, -1.40928211e-05, -4.81285248e-04,
          1.65721859e-05],
        [-1.69781182e-06, -7.35584319e-04,  3.03808404e-05,
          5.08110777e-04],
        [-6.98236833e-07, -1.36715914e-05, -7.52295945e-04,
          2.01436247e-05]],

       [[ 5.63142334e-34,  1.15953039e-35, -3.61479913e-35,
          1.93071706e-35],
        [ 2.34419656e-07, -2.77174096e-05, -9.45583957e-04,
          3.25604225e-05],
        [ 8.68770355e-07, -1.44529326e-03,  5.96907737e-05,
          9.98276544e-04],
        [ 3.57271806e-07, -2.68630520e-

In [5]:
trace_xi=[]
for i in range(16):
    trace_xi.append(np.trace(xi_trace_elements[i]))
trace_xi

[2.0416971296289144,
 3.643164389872514e-05,
 7.152343327544462e-05,
 0.005245550139946089,
 -2.513836696316774e-05,
 1.937617118301243,
 -0.02545656785642221,
 -0.023396040806611097,
 -5.040118343248609e-05,
 0.024900664101537462,
 1.9372051140922728,
 -0.04721565876083028,
 0.005245870647566781,
 0.024002152266897867,
 0.04691000221207688,
 2.040993058027729]

In [6]:
#trace_xi = [trace_xi]
trace_xi=np.array(trace_xi)
trace_xi=trace_xi.reshape(A,A)
trace_xi

array([[ 2.04169713e+00,  3.64316439e-05,  7.15234333e-05,
         5.24555014e-03],
       [-2.51383670e-05,  1.93761712e+00, -2.54565679e-02,
        -2.33960408e-02],
       [-5.04011834e-05,  2.49006641e-02,  1.93720511e+00,
        -4.72156588e-02],
       [ 5.24587065e-03,  2.40021523e-02,  4.69100022e-02,
         2.04099306e+00]])

In [7]:
from sklearn.preprocessing import normalize
trace_xi=normalize(trace_xi, axis=1, norm='l1') #0
#trace_xi=np.linalg.norm(trace_xi, axis = 0, keepdims = True)
print(trace_xi)


[[ 9.97384771e-01  1.77971386e-05  3.49397480e-05  2.56249164e-03]
 [-1.26546348e-05  9.75394979e-01 -1.28148168e-02 -1.17775491e-02]
 [-2.50830546e-05  1.23922629e-02  9.64084933e-01 -2.34977210e-02]
 [ 2.47779702e-03  1.13370049e-02  2.21571349e-02  9.64028063e-01]]


In [8]:
#trace_xi=np.array([[ 2.06602875e+00,  1.46673158e-05,  8.82090217e-06,
#         1.59563596e-03],
#       [-4.58013174e-06,  1.97929581e+00,  1.11646098e-01,
#        -2.53552484e-02],
#       [-2.57092376e-06, -1.11821012e-01,  1.97939871e+00,
#        -1.35737327e-02],
#       [ 1.59572095e-03,  2.45556983e-02,  1.49716489e-02,
#         2.06582300e+00]])
###iy non normalized
#trace_xi=np.array([[ 2.04169713e+00,  3.64316439e-05,  7.15234333e-05,
#         5.24555014e-03],
#       [-2.51383670e-05,  1.93761712e+00, -2.54565679e-02,
#        -2.33960408e-02],
#       [-5.04011834e-05,  2.49006641e-02,  1.93720511e+00,
#        -4.72156588e-02],
#       [ 5.24587065e-03,  2.40021523e-02,  4.69100022e-02,
#         2.04099306e+00]])
###
#trace_xi=np.array([[ 9.99224779e-01,  6.93264859e-06 , 4.18841229e-06,  7.57536857e-04],
# [-2.21515849e-06 , 9.35533297e-01 , 5.30127056e-02 ,-1.20375422e-02],
# [-1.24341480e-06 ,-5.28532821e-02 , 9.39874146e-01 ,-6.44420351e-03],
# [ 7.71762693e-04 , 1.16064881e-02 , 7.10895973e-03  ,9.80760717e-01]])
#####
#trace_xi=np.array([[ 9.99216925e-01,  7.09372037e-06 , 4.26615300e-06 , 7.71715522e-04],
# [-2.16421489e-06 , 9.35261629e-01 , 5.27552834e-02 ,-1.19809231e-02],
# [-1.22145981e-06 ,-5.31267689e-02 , 9.40423056e-01 ,-6.44895399e-03],
# [ 7.57362026e-04 , 1.16546402e-02  ,7.10585292e-03  ,9.80482145e-01]])
####iy trace:#
trace_xi=[[ 9.97384771e-01,  1.77971386e-05 , 3.49397480e-05 , 2.56249164e-03],
 [-1.26546348e-05  ,9.75394979e-01 ,-1.28148168e-02 ,-1.17775491e-02],
 [-2.50830546e-05 , 1.23922629e-02 , 9.64084933e-01 ,-2.34977210e-02],
 [ 2.47779702e-03 , 1.13370049e-02 , 2.21571349e-02 , 9.64028063e-01]]

#trace_xi=qi.SuperOp(trace_xi)
#trace_xi=qi.Qobj()
#print(trace_xi.is_cp())
#trace_xi=qi.Choi(trace_xi)
#trace_xi
trace_xi_p=qi.PTM(trace_xi)
print(trace_xi_p.is_cp())
trace_xi_k=qi.Kraus(trace_xi_p)
trace_xi_k


True


Kraus([[[-9.88836847e-01+3.65475358e-18j,
         -5.96373219e-03+1.16524234e-02j],
        [ 5.81014741e-03+1.17251060e-02j,
         -9.86187348e-01-1.28164751e-02j]],

       [[-5.24369155e-02+4.70149447e-16j,
         -2.12298065e-03+4.91143811e-02j],
        [-1.79882875e-03-4.87710513e-02j,
          5.25786054e-02+1.45438594e-04j]],

       [[-5.16276136e-02-5.59185676e-12j,
         -5.49655566e-04-5.57442262e-02j],
        [-2.26290124e-03+5.52589745e-02j,
          5.17368637e-02+1.36842988e-03j]],

       [[-3.63467077e-03+2.68838028e-14j,
          9.88967357e-02-3.40535891e-02j],
        [ 9.93122252e-02-3.52990240e-02j,
          2.83951362e-03-2.31441471e-03j]]],
      input_dims=(2,), output_dims=(2,))

In [9]:
#kraus=np.array([[[ 1.42332067e+00-1.34082755e-17j,
#          8.63045820e-03-5.26425220e-03j],
#        [-8.90972099e-03-4.76757292e-03j,
#          1.41991500e+00-8.01537442e-02j]],

#       [[-2.04156405e-01-9.66093367e-17j,
#         -6.23739686e-06-1.21670301e-05j],
#        [-7.22797613e-06+1.15931152e-05j,
#          2.03996025e-01-1.15153158e-02j]],

#       [[-9.11787603e-07-1.22945487e-18j,
#          1.10142304e-04-6.58833068e-05j],
#        [-1.12598705e-04-6.17291868e-05j,
#         -9.11612152e-07+3.42894424e-08j]],

#       [[-5.15198900e-09-4.77360364e-18j,
#          7.30184016e-04+4.12925515e-04j],
#        [ 1.30595995e-05+8.38319270e-04j,
#         -5.39051238e-09-1.75317375e-10j]]])
#kraus=np.array([[[ 9.82537468e-01+2.05937555e-18j,
#          5.95741975e-03-3.63398201e-03j],
#        [-6.15020073e-03-3.29111680e-03j,
#          9.80177402e-01-5.53306993e-02j]],

#       [[-1.59302428e-01+2.11730533e-17j,
#          8.95396998e-05-7.36947904e-06j],
#        [ 8.81397489e-05+1.54796173e-06j,
#          1.59178716e-01-8.98616078e-03j]],

 #      [[ 4.56219376e-04-9.76504911e-14j,
 #        -7.53973666e-02-4.63555433e-04j],
 #       [ 7.50548822e-02-3.78742725e-03j,
 #         4.56359033e-04-1.91845042e-05j]],

  #     [[-2.21892571e-04+9.87158444e-11j,
  #       -8.94079075e-03-5.85279733e-02j],
  #      [-1.22733398e-02-5.81209005e-02j,
  #       -2.08029237e-04+7.71436610e-05j]]])
#axis=1#
#kraus=np.array([[[ 9.82536234e-01+6.22484178e-18j,
#          5.95742529e-03-3.63399038e-03j],
#        [-6.15016657e-03-3.29112970e-03j,
#          9.80176404e-01-5.53306415e-02j]],

#       [[-1.58859530e-01+4.55562138e-17j,
#         -1.01662296e-04-1.77329673e-05j],
#        [-1.01719624e-04+2.28484157e-05j,
#          1.58736215e-01-8.95963849e-03j]],

 #      [[ 4.82651832e-04-3.36673528e-14j,
 #        -7.69186194e-02+2.49574277e-03j],
 #       [ 7.71538614e-02+1.83762625e-03j,
 #         4.82949519e-04-4.78509995e-06j]],

  #     [[-1.98403984e-04-3.21647191e-12j,
  #        7.78391188e-03-5.76906733e-02j],
  #      [ 1.09863795e-02-5.70009128e-02j,
  #       -1.88280044e-04-6.21355852e-05j]]])
#yi
kraus=np.array([[[-9.88836847e-01+3.65475358e-18j,
         -5.96373219e-03+1.16524234e-02j],
        [ 5.81014741e-03+1.17251060e-02j,
         -9.86187348e-01-1.28164751e-02j]],

       [[-5.24369155e-02+4.70149447e-16j,
         -2.12298065e-03+4.91143811e-02j],
        [-1.79882875e-03-4.87710513e-02j,
          5.25786054e-02+1.45438594e-04j]],

       [[-5.16276136e-02-5.59185676e-12j,
         -5.49655566e-04-5.57442262e-02j],
        [-2.26290124e-03+5.52589745e-02j,
          5.17368637e-02+1.36842988e-03j]],

       [[-3.63467077e-03+2.68838028e-14j,
          9.88967357e-02-3.40535891e-02j],
        [ 9.93122252e-02-3.52990240e-02j,
          2.83951362e-03-2.31441471e-03j]]])
###yi non normalized
#kraus=np.array([[[ 1.41239144e+00+8.58784282e-18j,
#          8.51134703e-03-1.66324508e-02j],
#        [-8.29082129e-03-1.67339961e-02j,
#          1.40845386e+00+1.83042531e-02j]],

#       [[ 2.27466958e-01-1.81614956e-17j,
#         -9.06184321e-06+3.37392088e-06j],
#        [-3.09926664e-06+8.44937203e-06j,
#         -2.28064189e-01-2.96374687e-03j]],

#       [[ 3.73299915e-06+3.52010990e-19j,
#         -1.28036577e-04+2.51299788e-04j],
#        [ 1.25927341e-04+2.52544441e-04j,
#          3.73925254e-06+3.24041865e-08j]],

#       [[-1.22540511e-08+5.86295326e-18j,
#         -6.08350102e-04-1.63220029e-03j],
#        [ 1.67296445e-03+4.81533733e-04j,
#         -1.71573257e-08+5.10609660e-09j]]])
###
print(kraus)
#print(kraus[0].round(3))
toplam = np.matmul(kraus[0].conj().T,kraus[0])+ np.matmul(kraus[1].conj().T,kraus[1])+ np.matmul(kraus[2].conj().T,kraus[2])+np.matmul(kraus[3].conj().T,kraus[3])
#toplam = np.matmul(kraus[0].round(2).conj().T,kraus[0].round(2))
#toplam = np.matmul(kraus[0].conj().T,kraus[0]+np.matmul(kraus[1].conj().T,kraus[1]))
#toplam
#a=kraus[0].round(5)
#toplam=np.matmul(a.conj().T,a)
toplam.round(3)

[[[-9.88836847e-01+3.65475358e-18j -5.96373219e-03+1.16524234e-02j]
  [ 5.81014741e-03+1.17251060e-02j -9.86187348e-01-1.28164751e-02j]]

 [[-5.24369155e-02+4.70149447e-16j -2.12298065e-03+4.91143811e-02j]
  [-1.79882875e-03-4.87710513e-02j  5.25786054e-02+1.45438594e-04j]]

 [[-5.16276136e-02-5.59185676e-12j -5.49655566e-04-5.57442262e-02j]
  [-2.26290124e-03+5.52589745e-02j  5.17368637e-02+1.36842988e-03j]]

 [[-3.63467077e-03+2.68838028e-14j  9.88967357e-02-3.40535891e-02j]
  [ 9.93122252e-02-3.52990240e-02j  2.83951362e-03-2.31441471e-03j]]]


array([[1.   +0.j, 0.   -0.j],
       [0.   +0.j, 0.995+0.j]])

In [10]:
from sympy.physics.quantum import TensorProduct
i = np.array([[1, 0], [0, 1]])
x = np.array([[0, 1], [1, 0]])
y = np.array([[0,-1j],[1j,0]])
z = np.array([[1, 0], [0,-1]])

In [11]:
from itertools import product
def coefficients(kraus_list,q_number):
    paulis = list(product([i,x,y,z],repeat=q_number))
    spaulis = list(product(['i','x','y','z'],repeat=q_number))
    #print(spaulis)
    result = []
    for k_index,kraus in enumerate(kraus_list,start=0):
        print(kraus)
        for index, pauli in enumerate(paulis, start=0):
            a = 1/2*(np.trace(np.matmul(kraus,pauli[0])))
            print(a)
            result.append((a,spaulis[index],k_index))
    return result

In [12]:
coef = coefficients(kraus,1)
coef

[[-0.98883685+3.65475358e-18j -0.00596373+1.16524234e-02j]
 [ 0.00581015+1.17251060e-02j -0.98618735-1.28164751e-02j]]
(-0.9875120975-0.0064082375499999985j)
(-7.679239000000018e-05+0.0116887647j)
(3.6341300000000167e-05-0.0058869398j)
(-0.0013247494999999998+0.006408237550000002j)
[[-0.05243692+4.70149447e-16j -0.00212298+4.91143811e-02j]
 [-0.00179883-4.87710513e-02j  0.05257861+1.45438594e-04j]]
(7.084494999999927e-05+7.271929700023507e-05j)
(-0.0019609047+0.00017166490000000006j)
(-0.0489427162-0.00016207595000000002j)
(-0.052507760449999996-7.271929699976493e-05j)
[[-0.05162761-5.59185676e-12j -0.00054966-5.57442262e-02j]
 [-0.0022629 +5.52589745e-02j  0.05173686+1.36842988e-03j]]
(5.4625050000003256e-05+0.0006842149372040716j)
(-0.0014062784029999999-0.00024262584999999726j)
(0.05550160035+0.0008566228369999999j)
(-0.051682238650000004-0.0006842149427959284j)
[[-0.00363467+2.68838028e-14j  0.09889674-3.40535891e-02j]
 [ 0.09931223-3.52990240e-02j  0.00283951-2.31441471e-03j]]
(-0

[((-0.9875120975-0.0064082375499999985j), ('i',), 0),
 ((-7.679239000000018e-05+0.0116887647j), ('x',), 0),
 ((3.6341300000000167e-05-0.0058869398j), ('y',), 0),
 ((-0.0013247494999999998+0.006408237550000002j), ('z',), 0),
 ((7.084494999999927e-05+7.271929700023507e-05j), ('i',), 1),
 ((-0.0019609047+0.00017166490000000006j), ('x',), 1),
 ((-0.0489427162-0.00016207595000000002j), ('y',), 1),
 ((-0.052507760449999996-7.271929699976493e-05j), ('z',), 1),
 ((5.4625050000003256e-05+0.0006842149372040716j), ('i',), 2),
 ((-0.0014062784029999999-0.00024262584999999726j), ('x',), 2),
 ((0.05550160035+0.0008566228369999999j), ('y',), 2),
 ((-0.051682238650000004-0.0006842149427959284j), ('z',), 2),
 ((-0.0003975785750000001-0.001157207354986558j), ('i',), 3),
 ((0.09910448045-0.034676306549999994j), ('x',), 3),
 ((-0.0006227174500000009-0.00020774475000000237j), ('y',), 3),
 ((-0.003237092195+0.001157207355013442j), ('z',), 3)]

In [13]:
from collections import defaultdict
d = defaultdict(complex)
for c, name, n in coef:
    #print(c,name, n)
    d[name] += abs(c)*abs(c)
 
d

defaultdict(complex,
            {('i',): (0.975223186856012+0j),
             ('x',): (0.011166688500827339+0j),
             ('y',): (0.0055116654975458975+0j),
             ('z',): (0.005483230502010648+0j)})